---

- name: Install requirements
  ansible.builtin.package:
    name: "{{ cicd_dependency_packages }}"
    state: present

- name: Install RPM on RedHat family
  when: ansible_facts.os_family == 'RedHat'
  block:

    - name: Download package
      ansible.builtin.get_url:
        url: "{{ cicd_repo }}/releases/download/{{ cicd_version }}/{{ cicd_package_rpm }}"
        dest: "/tmp/{{ cicd_package_rpm }}"
        mode: "0644"

    - name: Install package using dnf  # noqa command-instead-of-module
      ansible.builtin.command:
        cmd: rpm -i /tmp/{{ cicd_package_rpm }}
      changed_when: __rpm.rc == 0 or (__rpm.rc > 0 and __rpm.stderr is not search('is already installed'))
      failed_when: __rpm.rc > 0 and __rpm.stderr is not search('is already installed')
      register: __rpm

- name: Install DEB on Debian family
  when: ansible_facts.os_family == 'Debian'
  block:

    - name: Download package
      ansible.builtin.get_url:
        url: "{{ cicd_repo }}/releases/download/{{ cicd_version }}/{{ cicd_package_deb }}"
        dest: "/tmp/{{ cicd_package_deb }}"
        mode: "0644"

    - name: Install package using apt
      ansible.builtin.apt:
        deb: "/tmp/{{ cicd_package_deb }}"
        state: present
