---

- name: Get latest cicd release info
  ansible.builtin.uri:
    url: "{{ cicd_api + '/releases/latest' }}"
  check_mode: no
  register: cicd_version_info
  run_once: true

- name: Get latest release tag
  ansible.builtin.set_fact:
    cicd_version_latest: "{{ cicd_version_info.json.tag_name }}"

- name: Replace 'latest' by the actual version
  ansible.builtin.set_fact:
    cicd_version: "{{ cicd_version_latest }}"
  when: cicd_version == 'latest'

- name: Get all cicd releases info
  ansible.builtin.uri:
    url: "{{ cicd_api + '/releases?per_page=1000' }}"
  run_once: true
  check_mode: no
  register: cicd_version_info

- name: Get version information
  ansible.builtin.set_fact:
    cicd_version_info: "{{ cicd_version_info.json | json_query(qq) | first }}"
  vars:
    qq: "[?tag_name=='{{ cicd_version }}']"

- name: Show cicd release
  ansible.builtin.debug:
    msg:
      - "cicd latest release    : {{ cicd_version_latest }}"
      - "cicd requested release : {{ cicd_version }}"
